<!DOCTYPE HTML>

<html>
<body>

	
								 
<P> This user agreement is concluded between you - the Client, the Advertiser and the CPA - the network. </ P>
                <P> <b> Customer </ b> - a person who, through the activities of the CPA network, attracted by promotion methods, to purchase / alienate the offerings for goods and / or services offered by the Advertiser, having the intention to order or purchase or order, acquire or Using goods solely for personal, family, home and other needs not related to the performance of entrepreneurial activities. </ P>
                <P> <b> Advertiser </ b> is a person who wishes to place an offer in the CPA network, with the purpose of alienating a particular product and / or service. </ P>
                <P> <b> CPA network </ b> (short for Cost Per Action, that is, payment for an action) is an electronic business environment in which a contractual relationship is created between the Advertiser and the CPA network, in virtue of which the Advertiser Offers offers for goods and / or services, and CPA-network, in turn, attracts customers interested in purchasing of the offerings permitted by the Advertiser methods. The end result of such activity is the acquisition of goods and / or services by the Client, through the CPA network. </ P>
                <P> <b> Parties </ b> - Client, Advertiser, CPA network. </ P>
                <P> <b> Website </ b> - an online resource of an online store that has the domain name m.womenpurse.ru, which is under organizational management and belongs to the Advertiser, under private ownership. </ P>
                <P> <b> Public Offer </ b> is an offer addressed to an undefined circle of persons or several specific persons by the administration, which expressly and specifically expresses the intention of the person who made the offer to consider himself a concluding user agreement with the addressee to whom the offer is accepted. </ P>
                <P> <b> Acceptance </ b> is the complete acceptance by one of the Parties of the terms of the public offer of the CPA-network for the conclusion of this user agreement. Acceptance of a public offer occurs at the time when the Site is used (including for informational purposes) and its services (services). </ P>
 
                <P class = "no-margin"> <b> 1. General </ b> </ p>
                <P class = "no-margin"> 1.1. This User Agreement (hereinafter referred to as the "Agreement") defines the general rules for visiting, using the services and the general rules of conduct on the Site by the Client and regulates the civil and legal relations that develop between the Client and the Advertiser, as well as the Client, the Advertiser and the CPA network In the process of their interaction. </ P>
                <P class = "no-margin"> 1.2. This Agreement can be changed unilaterally by decision of the CPA network and / or the Advertiser. CPA-network and / or the Advertiser does not bear the obligation of personal notification of the Client about such changes. The new version of the Agreement comes into force from the moment of the purchase of the goods / services of the Advertiser by the Client. </ P>
                <P class = "no-margin"> 1.3. Terms of the Agreement apply to all Clients of the site, without exceptions. </ P>
                <P> 1.4. The client, beginning to use the Site, confirms the fact that he has familiarized himself with the provisions of this Agreement in a sound mind and with clear memory, understands them fully and accepts the conditions for using the Site to the fullest. If you disagree with the provisions of this Agreement (in whole or in part), the person expressing such will is not entitled to use the information field of the Site. </ P>
 
                <P class = "no-margin"> <b> 2. Regulation of interaction between parties </ b> </ p>
                <P class = "no-margin"> 2.1. The implementation of the services and (or) opportunities provided by the Site does not provide the Client any exclusive rights and privileges. </ P>
                <P class = "no-margin"> 2.2. The parties to this Agreement have reached an agreement that the CPA-network has the right to place ad units, banners, ads in any of its areas on the Site, including where the information published by the Customer is placed, without the Customer's additional consent. </ P>
                <P class = "no-margin"> 2.3. The information placed on the Site by the CPA network is the result of the intellectual activity of the CPA network and all the proprietary and personal non-property rights to such information are owned by the CPA network, until it is determined otherwise. At the same time, the Client does not have any exclusive rights to the result of the intellectual activity of the CPA network, expressed in graphic, text, audio-video form, placed by the CPA network on the Site. </ P>
                <P class = "no-margin"> 2.4. CPA-network does not bear any obligations to protect the violated rights of the Client, in the context of settlement of disputes arising on this ground, including in court. </ P>
                <P class = "no-margin"> 2.5. CPA-network is not the owner / manufacturer of goods and / or services placed on the Site and is not responsible for violation of the Client's rights. The purpose of the CPA network under this Agreement is to attract potential customers interested in purchasing goods and / or services that are authorized by the Advertiser. The end result of such activity is the acquisition of goods and / or services by the Client, through the CPA network. </ P>
                <P class = "no-margin"> 2.6. Infringement by the Client or the Advertiser of the copyrights belonging to the CPA-network and (or) to other persons, entails for the infringer the responsibility provided by provisions of the current legislation of the Russian Federation. </ P>
                <P class = "no-margin"> 2.7. In case of revealing infringement of copyrights by the Client, by illegal placement of materials not belonging to the Client, the CPA-network withdraws such materials from free access, at the first request of the legal right holder. </ P>
                <P class = "no-margin"> 2.8. The client is prohibited from posting on the Site information that directly or indirectly contains the generally accepted signs of pornography, insulting, infringing, damaging someone's dignity, containing calls for violence, brutality and other actions that lead to violations of the laws in force, certain territorial jurisdictions, Containing malicious software and (or) other information that may harm third parties. </ P>
                <P class = "no-margin"> 2.9. In the event of a violation of the conditions of 2.8. Of this Agreement and the failure to comply with the requirements of the CPA network, including the withdrawal of such information from public access, the Site's customers are liable under the provisions of this Agreement and (or) the current legislation of the Russian Federation. CPA-network in this case, has the right to remove the mentioned in 2.8. Information yourself. </ P>
                <P class = "no-margin"> 2.10. CPA-network is not responsible for the results of the Client's visits to external (external) resources, links to which can be posted on the Site. Results are understood as any result, regardless of its nature, as well as the one from which the Client incurred any material losses, moral damage and other negative manifestations. </ P>
                <P> 2.11. The procedure for remote trading, the rights and obligations of the parties to the agreement, as well as third parties, specific requirements for the processes of interaction between the Parties and the design of advertising platforms, are regulated in the normative order - the Federal Law "On Advertising", the Rules for Remote Trading approved by the Decree of the Government of the Russian Federation Federation № 612 from 27.09.2007, as well as other normative acts and this Agreement. </ P>
 
                <P class = "no-margin"> <b> 3. Rights and obligations of the Advertiser </ b> </ p>
                <P class = "no-margin"> 3.1. The advertiser is obliged to offer the Client services for the delivery of goods by sending them by postal items or by transport, indicating the method of delivery used and the mode of transport. </ P>
                <P class = "no-margin"> 3.2. The advertiser is obliged to inform the Client about the need to use qualified specialists for connecting, setting up and commissioning technically complex products that can not be put into operation without the participation of relevant specialists in accordance with technical requirements. </ P>
                <P class = "no-margin"> 3.3. The advertiser has no right to perform additional works (render services) without the consent of the Client for a fee. </ P>
                <P class = "no-margin"> 3.4. The advertiser is obliged to provide the Customer with information about the main consumer properties of the goods and the address (location) of the Advertiser, about the place of manufacture of the goods, the full name of the advertiser, the price and conditions of the contract before the conclusion of the contract of retail sale (hereinafter referred to as the "Contract"). Purchase of goods, its delivery, service life, shelf life and warranty period, the procedure for payment for the goods, as well as the period during which the proposal to enter into the Agreement is valid. </ P>
                <P class = "no-margin"> 3.5. The advertiser at the time of delivery of the goods must inform the Client in writing the following information (for imported goods - in Russian): </ p>
                <P class = "no-margin>" 3.5.1. The name of the technical regulation or other designation established by the legislation of the Russian Federation on technical regulation and indicating the mandatory confirmation of the conformity of the goods; </ p>
<P class = "no-margin"> 3.5.2. Information on the main consumer properties of the goods (works, services), and with respect to food products - information on the composition (including the names used in the process of food production of food additives, biologically active additives, information on the presence in food products of components obtained with application Genetically engineered organisms), nutritional value, purpose, conditions of use and storage of food products, methods of making ready meals, weight (volume), date and place of manufacture and Packaging (packaging) of food, as well as information on contraindications for their use in certain diseases; </p>
                <P class = "no-margin"> 3.5.3. Price in rubles and conditions for the acquisition of goods (work performance, services); </ p>
                <P class = "no-margin"> 3.5.4. Information about the warranty period, if it is installed; </ p>
                <P class = "no-margin"> 3.5.5. Rules and conditions for the effective and safe use of goods; </ p>
                <P class = "no-margin"> 3.5.6. Information about the service life or the expiry date of the goods, as well as information about the necessary actions of the Customer after the expiration of the specified terms and possible consequences if such actions are not performed, if the goods after the expiration of the indicated terms pose a danger to the life, health and property of the Client or become unsuitable for the intended use ; </ P>
                <P class = "no-margin"> 3.5.7. Location (address), business name (name) of the manufacturer (Advertiser), location (address) of the organization (s) authorized by the manufacturer (Advertiser) to accept claims from the Client and repair and maintain the goods, for the imported goods - country name The origin of the goods; (See text in the previous wording) </ p>
                <P class = "no-margin"> 3.5.8. Information on mandatory confirmation of the conformity of goods (services) with mandatory requirements ensuring their safety for life, health of the Client, the environment and preventing damage to the Client's property in accordance with the legislation of the Russian Federation; </ p>
                <P class = "no-margin"> 3.5.9. Information on the rules for the sale of goods (works, services); </ p>
                <P class = "no-margin"> 3.5.10. Information about a particular person who will perform the work (provide the service), and information about him, if this matters according to the nature of the work (service); </ p>
                <P class = "no-margin"> 3.5.11 information on the energy efficiency of goods for which the requirement for the availability of such information is determined in accordance with the legislation of the Russian Federation on energy conservation and on improving energy efficiency. </ P>
                <P class = "no-margin"> 3.6. The advertiser is obliged to provide information to the Customer if the goods purchased by the Customer were in use or in which the deficiency was eliminated. </ P>
                <P class = "no-margin"> 3.7. The advertiser is obliged to inform the Client about the goods, including the conditions of its operation and the storage rules, is communicated to the Customer by placing on the product, on electronic carriers attached to the goods, in the product itself (on the electronic board inside the goods in the menu section), on the packaging, Label, label, in technical documentation or in any other way established by the legislation of the Russian Federation. </ P>
                <P class = "no-margin"> 3.8. The advertiser is obliged to inform the Customer about the period during which the offer to sell the goods / services on the Site is valid. </ P>
                <P class = "no-margin"> 3.9. The advertiser has the right to both accept and reject the Client's offer to forward the goods by postal mail to the "Demand" account. </ P>
                <P class = "no-margin"> 3.10. The advertiser is obliged to ensure the confidentiality of personal data about the Client in accordance with the legislation of the Russian Federation in the field of personal data. </ P>
                <P class = "no-margin"> 3.11. The advertiser provides the Client with catalogs, booklets, brochures, photographs or other information materials containing full, reliable and accessible information characterizing the offered goods. </ P>
                <P class = "no-margin"> 3.12. If the Client refuses the goods, the Advertiser is obliged to return to him the amount paid by the Customer in accordance with the Contract, with the exception of the Advertiser's expenses for the delivery of the returned goods from the Customer, not later than 10 days from the date of the request of the Customer. </ P>
                <P class = "no-margin"> 3.13. If the Agreement is concluded on the condition that the goods are delivered to the Client, the Advertiser is obliged to deliver the goods within the period specified by the Contract to the place specified by the Customer, and if the place of delivery of the goods by the Client is not indicated, then to the place of his residence. </ P>

<P class = "no-margin"> 3.14. The advertiser is obliged to transfer the goods to the Customer in the manner and terms specified in the Contract. </ P>
                <P class = "no-margin"> 3.15. The advertiser is obliged to deliver to the Customer the goods, the quality of which corresponds to the Contract and the information provided to the Client at the conclusion of the Contract, as well as information brought to its attention when transferring the goods (in technical documentation attached to the product, on labels, by marking or by other means provided for For certain types of goods). </ P>
                <P class = "no-margin"> 3.16. If the Advertiser, when signing the Agreement, was informed by the Client of the specific purposes for the purchase of the goods, the Advertiser is obliged to transfer to the Client the goods suitable for use in accordance with these purposes. </ P>
                <P class = "no-margin"> 3.17. The costs for the refund of the amount paid by the Customer in accordance with the Agreement shall be borne by the Advertiser. </ P>
                <P> 3.18. Payment for the goods by the Customer by transferring funds to the account of a third party indicated by the Advertiser does not relieve the Advertiser of the obligation to return the amount paid by the Customer when the goods are returned by the Customer both of proper and improper quality. </ P>
 
                <P class = "no-margin"> <b> 4. Rights and obligations of the Client </ b> </ p>
                <P class = "no-margin>" 4.1. The customer has the right to refuse the goods at any time prior to its transfer, and after the transfer of the goods - within 7 days. </ P>
                <P class = "no-margin"> 4.2. The customer has the right to refuse the goods within 3 months from the moment of transfer of the goods, in case information on the order and terms of returning the goods of the proper quality was not provided in writing at the time of delivery of the goods. </ P>
                <P class = "no-margin"> 4.3. Return of good quality goods is possible in the event that its presentation, consumer properties are preserved, as well as a document confirming the fact and conditions for the purchase of the said goods. The Client's lack of this document does not deprive him of the opportunity to refer to other evidence of the purchase of goods from this Advertiser. </ P>
                <P class = "no-margin"> 4.4. The customer shall not be entitled to refuse from the goods of proper quality having individually defined properties, if the said goods can only be used by the Customer who acquires it. </ P>
                <P class = "no-margin"> 4.5. The customer is obliged to re-pay the cost of the delivery of goods, if the delivery of the goods is made within the terms established by the Contract, but the goods were not transferred to the Client through his fault, the subsequent delivery is made in a new time agreed with the Advertiser. </ P>
                <P class = "no-margin"> 4.6. If the goods are transferred to the Customer in violation of the terms of the Agreement concerning the quantity, assortment, quality, completeness, packaging and (or) packaging of the goods, the Customer may notify the Advertiser of such violations within 20 days after receipt of the goods. </ P>
                <P class = "no-margin"> 4.7. If defects in the goods are found in respect of which the warranty terms or expiration dates are not established, the Client shall be entitled to present claims for defects of the goods within a reasonable time, but within 2 years from the date of its transfer to the Client, if longer periods are not established by regulatory enactments or the Treaty. </ P>
                <P class = "no-margin"> 4.8. The Client has the right to present requirements to the Advertiser in respect of defects of the goods, if they are found during the warranty period or the expiry date. </ P>
                <P class = "no-margin"> 4.9. The client who sold the goods of inadequate quality, if this was not agreed by the Advertiser, may at his option demand: </ p>
                <P class = "no-margin"> a) free of charge elimination of defects in the goods or reimbursement of expenses for their correction by the Customer or a third party; </ p>
                <P class = "no-margin"> b) a commensurate reduction in the purchase price; </ p>
                C) substituting for a product of a similar brand (model, article) or for the same goods of another brand (model, article) with the corresponding recalculation of the purchase price. At the same time, in respect of technically complex and expensive products, these Customer's requirements are subject to satisfaction in case of detection of significant shortcomings. </ P>
                <P class = "no-margin"> 4.10. The client, instead of presenting the requirements specified in clause 4.9 of this Agreement, has the right to refuse to perform the Contract and demand the return of the amount paid for the purchased goods. At the request of the Advertiser and at his expense, the Customer must return the defective product. </ P>
                <P class = "no-margin"> 4.11. The Client has the right to demand full compensation for losses caused to him by the sale of goods of inadequate quality. Losses are reimbursed within the time limits established by the Law of the Russian Federation "On Protection of Consumer Rights" to meet the relevant requirements
 
<P class = "no-margin"> 4.12. The Client has the right to refuse to execute the Contract and demand compensation for the losses incurred, & nbsp; if the Advertiser refuses to transfer the goods. </ P>
                <P class = "no-margin"> 4.13. When returning goods of inadequate quality, the Customer's lack of a document confirming the fact and conditions for the purchase of the goods does not deprive him of the opportunity to refer to other evidence of the purchase of the goods from the Advertiser. </ P>
                <P class = "no-margin"> 4.14. Refusal or evasion of the Advertiser from drawing up the waybill or the certificate does not deprive the Client of the right to demand the return of the goods and (or) return of the amount paid by the Client in accordance with the Contract. </ P>
                <P class = "no-margin"> 4.15. The Customer has the right to refuse to pay for additional works (services) that are not stipulated by the Contract, and if they are paid, the Client has the right to demand from the Advertiser a refund of the amount paid above the specified amount. </ P>
                <P class = "no-margin"> 4.16. In case of using the results of intellectual property of the CPA network - the materials of the Site, for any purpose, the Client is obliged beforehand, before placing such materials, to obtain the permission of the CPA network for this. If you have permission from CPA-network, the Customer must display the full name and domain name of the source in the following format: online store m.womenpurse.ru. The hyperlink must be active and direct, when you click on which you go to a specific page of the Site from which the material is borrowed. </ P>
                <P> 4.17. By analogy with the instructions set out in § 4.16. Of this Agreement, the Client undertakes to act, in the case of using the results of intellectual property, that it belongs to third parties. The method and procedure for implementation is specified in the process of negotiations with the owner of the materials. </ P>
 
                <P class = "no-margin"> <b> 5. Responsibility of the parties </ b> </ p>
                <P class = "no-margin"> 5.1. CPA-network is not liable for the actions of the Client, which entailed the violation of the rights of third parties, except for cases determined by the current legislation of the Russian Federation. </ P>
                <P class = "no-margin"> 5.2. CPA-network is not responsible for the content of information posted by the Advertiser and / or the Customer. </ P>
                <P class = "no-margin"> 5.3. CPA-network is not responsible for the content of the feedback from the Clients of the Site. Testimonials of the Site's Customers are subjective opinions of their authors, in no way claiming to be objective. They may not coincide with public opinion and do not correspond to reality. </ P>
                <P class = "no-margin"> 5.4. The decision on the issue / non-issuance of personal data is accepted by the CPA network only on the basis of a request sent by the person of the CPA network in accordance with the procedure established by applicable law. </ P>
                <P class = "no-margin"> 5.5. CPA-network has the right not to respond to inquiries, appeals and letters, that they do not contain requisites of the contacting person (full name, contact details). </ P>
                <P class = "no-margin"> 5.6. CPA-network is not responsible for the registration data that were indicated by the Customer when interacting with the information field of the Site. </ P>
                <P> 5.7. CPA network has the right to limit, without explanation of reasons, blocking the Client's access (including unregistered) to the Site, with partial or complete removal of information that was posted by the Client on the Site. CPA-network undertakes to consider the claim, executed in accordance with the procedure provided for by section 5 of the agreement, within 30 (thirty) calendar days from the date of receipt. </ P>
 
                <P class = "no-margin"> <b> 6. Settlement of disputes </ b> </ p>
                <P class = "no-margin"> 6.1. If the information on the Site containing information containing the results of intellectual property belonging to third parties is found on the Site, the copyright owner is obliged to: </ p>
                <P class = "no-margin"> 6.1.1. Draw up a claim indicating the actual and regulatory grounds that enable the CPA network to withdraw information from public access. </ P>
                <P class = "no-margin"> 6.1.2. Attach to the claim evidence of the originality of the result of intellectual property (original copy, other documents confirming the right of ownership of the copyright object). </ P>
                <P class = "no-margin"> 6.1.3. Send the package of documents mentioned in the provisions of cl. 6.1.1., 6.1.2. Of this Agreement, to the electronic mail box CPA-network </ p>
                <P> 6.2. Claims of the Customer on the quality of service, products, as well as other comments, should be sent to the Advertiser on the electronic mail box </ p>
 
                <P class = "no-margin"> <b> 7. Other conditions </ b> </ p>
 
<P class = "no-margin"> 7.1. All possible situations, disputes arising from the relationship between the Client and the Advertiser, as well as the Client, the Advertiser and the CPA network, which are not settled by this Agreement, shall be resolved in accordance with the rules of the current legislation of the Russian Federation. </ P>
                <P class = "no-margin"> 7.2. The Parties to this Agreement are aware of the scope of the rights and obligations generated by the relationships of the persons mentioned in this Agreement and give full account of their actions, understanding the legal nature of the consequences of such actions to the full. </ P>
                <P class = "no-margin"> 7.3. Inaction on the part of the CPA network in case of violation of the provisions of the Agreement by any of the Clients does not deprive the CPA network of the right to take later appropriate actions in defense of its interests and protection of the rights protected by law. </ P>
                
                
            </ Div>
        </ Div>
    </ Div>
</ Div>


	

	</body>
</html>